# Generated by Django 4.1.3 on 2023-03-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POIDATA",
            fields=[
                (
                    "POI_DATA_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Point Of Interest Data ID",
                    ),
                ),
                (
                    "POI_DATA_Type",
                    models.CharField(
                        max_length=50, verbose_name="Point Of Interest Data Type"
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="photo_images/",
                        verbose_name="Photo File",
                    ),
                ),
                ("uploaded_on", models.DateField(verbose_name="Upload Date")),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "reoccurrence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ["...", "1-Months"],
                            ["...", "2-Months"],
                            ["...", "3-Months"],
                            ["...", "4-Months"],
                            ["...", "5-Months"],
                            ["...", "6-Months"],
                            ["...", "7-Months"],
                            ["...", "8-Months"],
                            ["...", "9-Months"],
                            ["...", "10-Months"],
                            ["...", "11-Months"],
                            ["...", "1 Year"],
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Repeat",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audio_files/",
                        verbose_name="Upload Audio",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "isAudioPresent",
                    models.BooleanField(default=False, verbose_name="Audio Present"),
                ),
                ("isActive", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={"verbose_name": "POI Data", "verbose_name_plural": "POI DATA's",},
        ),
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "POI_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Point of Interest ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        default=0,
                        max_digits=15,
                        verbose_name="Location Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        default=0,
                        max_digits=15,
                        verbose_name="Location Longitude",
                    ),
                ),
                (
                    "data_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poi_data",
                        to="ontarioparks.poidata",
                    ),
                ),
            ],
            options={"verbose_name": "POI", "verbose_name_plural": "POI's",},
        ),
    ]
