# Generated by Django 4.1.7 on 2023-03-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontarioparks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='data_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_data', to='ontarioparks.poidata'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=15, verbose_name='Location Latitude'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=15, verbose_name='Location Longitude'),
        ),
        migrations.AlterField(
            model_name='poidata',
            name='reoccurrence',
            field=models.CharField(blank=True, choices=[['...', '1-Months'], ['...', '2-Months'], ['...', '3-Months'], ['...', '4-Months'], ['...', '5-Months'], ['...', '6-Months'], ['...', '7-Months'], ['...', '8-Months'], ['...', '9-Months'], ['...', '10-Months'], ['...', '11-Months'], ['...', '1 Year']], default=None, max_length=50, null=True, verbose_name='Repeat'),
        ),
    ]
